name: 'Setup Python and Dependencies'
description: 'Setup uv with Python 3.13 and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install the latest version of uv and set the python version to 3.13
      uses: astral-sh/setup-uv@v6
      with:
        python-version: 3.13
        activate-environment: true

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --group all
        uv pip install 'git+https://github.com/google/A2A#subdirectory=samples/python'