name: Documentation

on:
  push:
    branches: [main]
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  pull_request:
    paths:
      - mkdocs.yml
      - 'docs/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build docs
        if: github.event_name == 'pull_request'
        run: mkdocs build -s

      - name: Publish docs
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        run: mkdocs gh-deploy
