name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  run-linter:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python
        with:
          dependency-groups: 'lint'
          install-a2a: 'false'

      # In case of considering adding caching, check the following PR first:
      # https://github.com/mozilla-ai/any-agent/pull/186
      - name: pre-commit
        run: uv run pre-commit run --all-files --verbose
